# Generated by Django 5.0.1 on 2025-12-06 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("git", "Git"),
                    ("python", "Python"),
                    ("general", "General"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="feedback_comment",
            field=models.TextField(blank=True, default="", verbose_name="피드백 코멘트"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_helpful",
            field=models.BooleanField(blank=True, null=True, verbose_name="도움 여부"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_chat_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="생성일시"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "created_at"], name="chat_messag_user_id_ecc172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "category"], name="chat_messag_user_id_900ca6_idx"
            ),
        ),
    ]
